language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - REPORT_EXIT_STATUS=1 TESTS="-q --show-diff" TEST_PHP_EXECUTABLE=php

before_script:
  - sudo bash tests/bootstrap.sh

install:
  - phpize
  - sed -i -re 's|-(@if test ! -z "\$\(PHP_EXECUTABLE\)")|\1|' Makefile.global
  - sed -i -re '/TESTS/a \\t\tTEST_RESULT_EXIT_CODE=$$?; \\' Makefile.global
  - sed -i -re '/rm \$\(top_builddir\)\/tmp-php\.ini; \\/a \\t\texit $$TEST_RESULT_EXIT_CODE; \\' Makefile.global
  - egrep '^test:' -A 12 Makefile.global
  - ./configure
  - egrep '^test:' -A 12 Makefile
  - make

script: make test

notifications:
  email:
    - gasol.wu+travis@gmail.com
