language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - REPORT_EXIT_STATUS=1 TESTS="-q --show-diff" TEST_PHP_EXECUTABLE=php

before_script:
  - bash tests/bootstrap.sh

install:
  - phpize
  - sed -i'' -re 's|-(@if test ! -z "\$\(PHP_EXECUTABLE\)")|\1|' Makefile.global
  - ./configure
  - make

script: make test

notifications:
  email:
    - gasol.wu+travis@gmail.com
